<div class="container">
    <h3>New user login</h3>

    <?php
        echo Phalcon\Tag::form(array('users/register', 'method' => 'POST', 'name' => 'registration_form',
                'ng-model' => 'registration_form'))
    ?>

        <div class="form-group">
            <label for="first_name">First Name</label>
            <div class="input-group">
                <input type="text" class="form-control" name="first_name" id="first_name" ng-model="first_name"
                    ng-minlength="3"/>
            </div>
        </div>

        <div class="form-group">
            <label for="last_name">Last Name</label>
            <div class="input-group">
                <input type="text" class="form-control" name="last_name" id="last_name" ng-model="last_name"
                       ng-minlength="3"/>
            </div>
        </div>

        <div class="form-group">
            <label for="email">Email</label>
            <div class="input-group">
                <input type="text" class="form-control" name="email" id="email" ng-model="email" />
            </div>
        </div>
        <div class="form-group">
            <button class="btn btn-primary">Submit</button>
        </div>
    <?php
        echo Phalcon\Tag::endForm();
    ?>
</div>